/** Canonical IPC channel names shared by main and preload. */
export const IPC = {
  steering: {setModel:'steering:set-model',preview:'steering:preview',history:'steering:history',send:'steering:send',cancel:'steering:cancel',withdraw:'steering:withdraw',update:'steering:update'},
  harness: {
    detect: 'harness:detect',
    probe: 'harness:probe',
    installOffer: 'harness:install-offer',
    startInstall: 'harness:start-install',
    startLogin: 'harness:start-login',
    cancelLogin: 'harness:cancel-login',
    logout: 'harness:logout',
    accounts: 'harness:accounts',
    addAccount: 'harness:add-account',
    switchAccount: 'harness:switch-account',
    removeAccount: 'harness:remove-account',
    accountsChanged: 'harness:accounts-changed',
    terminalInput: 'harness:terminal-input',
    terminalResize: 'harness:terminal-resize',
    loginEvent: 'harness:login-event',
    terminalData: 'harness:terminal-data',
  },
  build: {
    list: 'build:list',
    get: 'build:get',
    rename: 'build:rename',
    critique: 'build:critique',
    reference: 'build:reference',
    start: 'build:start',
    resume: 'build:resume',
    trust: 'build:trust',
    stop: 'build:stop',
    active: 'build:active',
    log: 'build:log',
    prompt: 'build:prompt',
    report: 'build:report',
    exportBuild: 'build:export',
    importBuild: 'build:import',
    deleteBuilds: 'build:delete',
    pickWorkspace: 'build:pick-workspace',
    defaultWorkspace: 'build:default-workspace',
    readStream: 'build:read-stream',
    update: 'build:update',
  },
  attachment: { add: 'attachment:add', pick: 'attachment:pick', preview: 'attachment:preview', remove: 'attachment:remove', openFolder: 'attachment:open-folder' },
  context: { droppedFolder: 'context:dropped-folder', pickFolder: 'context:pick-folder', openFolder: 'context:open-folder' },
  media: { base: 'media:base' },
  onboarding: {
    get: 'onboarding:get',
    complete: 'onboarding:complete',
    reset: 'onboarding:reset',
  },
  play: { start: 'play:start', stop: 'play:stop', state: 'play:state' },
  report: {
    list: 'report:list',
    get: 'report:get',
    create: 'report:create',
    rename: 'report:rename',
    addBuilds: 'report:add-builds',
    removeBuilds: 'report:remove-builds',
    refresh: 'report:refresh',
    remove: 'report:delete',
    markdown: 'report:markdown',
    exportJson: 'report:export-json',
    exportMarkdown: 'report:export-markdown',
    importReport: 'report:import',
  },
} as const

export type IpcChannel = {
  [Area in keyof typeof IPC]: (typeof IPC)[Area][keyof (typeof IPC)[Area]]
}[keyof typeof IPC]
