/** Canonical IPC channel names shared by main and preload. */
export const IPC = {
  steering: {setModel:'steering:set-model',preview:'steering:preview',history:'steering:history',send:'steering:send',cancel:'steering:cancel',withdraw:'steering:withdraw',update:'steering:update'},
  harness: {
    detect: 'harness:detect',
    probe: 'harness:probe',
    installOffer: 'harness:install-offer',
    startInstall: 'harness:start-install',
    startLogin: 'harness:start-login',
    cancelLogin: 'harness:cancel-login',
    logout: 'harness:logout',
    accounts: 'harness:accounts',
    addAccount: 'harness:add-account',
    switchAccount: 'harness:switch-account',
    removeAccount: 'harness:remove-account',
    accountsChanged: 'harness:accounts-changed',
    terminalInput: 'harness:terminal-input',
    terminalResize: 'harness:terminal-resize',
    loginEvent: 'harness:login-event',
    terminalData: 'harness:terminal-data',
  },
  loop: {
    lead: 'loop:lead',
    list: 'loop:list',
    get: 'loop:get',
    rename: 'loop:rename',
    critique: 'loop:critique',
    reference: 'loop:reference',
    start: 'loop:start',
    resume: 'loop:resume',
    trust: 'loop:trust',
    stop: 'loop:stop',
    active: 'loop:active',
    log: 'loop:log',
    prompt: 'loop:prompt',
    report: 'loop:report',
    exportRun: 'loop:export',
    importRun: 'loop:import',
    deleteRuns: 'loop:delete',
    pickWorkspace: 'loop:pick-workspace',
    defaultWorkspace: 'loop:default-workspace',
    readStream: 'loop:read-stream',
    update: 'loop:update',
  },
  attachment: { add: 'attachment:add', pick: 'attachment:pick', preview: 'attachment:preview', remove: 'attachment:remove', openFolder: 'attachment:open-folder' },
  context: { droppedFolder: 'context:dropped-folder', pickFolder: 'context:pick-folder', openFolder: 'context:open-folder' },
  media: { base: 'media:base' },
  onboarding: {
    get: 'onboarding:get',
    complete: 'onboarding:complete',
    reset: 'onboarding:reset',
  },
  play: { start: 'play:start', stop: 'play:stop', state: 'play:state' },
  report: {
    list: 'report:list',
    get: 'report:get',
    create: 'report:create',
    rename: 'report:rename',
    addRuns: 'report:add-runs',
    removeRuns: 'report:remove-runs',
    refresh: 'report:refresh',
    remove: 'report:delete',
    markdown: 'report:markdown',
    exportJson: 'report:export-json',
    exportMarkdown: 'report:export-markdown',
    importReport: 'report:import',
  },
} as const

export type IpcChannel = {
  [Area in keyof typeof IPC]: (typeof IPC)[Area][keyof (typeof IPC)[Area]]
}[keyof typeof IPC]
