import fs from 'node:fs'
import path from 'node:path'
import { ENGINE_DEPS, ENGINE_DEV_DEPS, engineContract, SRC_DIRS } from '../shared/engine-stack'
import {
  ownedWorkspaceDirectory,
  writeWorkspaceFileSafely,
  type OwnedWorkspaceIdentity,
} from './owned-workspace-write'

/**
 * The parts of the engine stack that touch disk.
 *
 * The contract and the gate rules are plain text and live in `shared/` so the
 * renderer can show the same rubric the critic is given; only the scaffolding
 * needs `node:fs`, so only it lives here.
 */
export { engineContract, engineGateRules } from '../shared/engine-stack'

/**
 * The gate. Static checks only: it never builds or runs the game, so it costs
 * nothing and cannot be flaked by a broken build.
 *
 * The app rewrites this file every round on purpose. It is the one thing in
 * the workspace a worker has an incentive to weaken — a gate that can be
 * edited to pass is not a gate.
 */
export const GATE_SCRIPT = `#!/usr/bin/env node
// Generated by Gauntlet Gamesmith. Rewritten every round — edits will not survive.
import fs from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const DEPS = ${JSON.stringify(ENGINE_DEPS)}
const BANNED_DEPS = /^(react|react-dom|@react-three\\/|@types\\/react)/

function walk(dir) {
  const out = []
  let entries
  try {
    entries = fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    const rel = path.posix.join(dir, entry.name)
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
    if (entry.isDirectory()) out.push(...walk(rel))
    else if (/\\.(ts|tsx|js|mjs)$/.test(entry.name)) out.push(rel)
  }
  return out
}

const files = walk('src')
const source = new Map(files.map((f) => [f, fs.readFileSync(path.join(ROOT, f), 'utf8').split(/\\r?\\n/)]))
const checks = []

function scan(id, why, pattern, filter) {
  const violations = []
  for (const [file, lines] of source) {
    if (filter && !filter(file)) continue
    lines.forEach((line, i) => {
      if (line.trim().startsWith('//') || line.trim().startsWith('*')) return
      if (pattern.test(line)) violations.push({ file, line: i + 1, text: line.trim().slice(0, 160) })
    })
  }
  checks.push({ id, why, ok: violations.length === 0, violations })
}

const under = (prefix) => (file) => file.startsWith(prefix)
const notUnder = (prefix) => (file) => !file.startsWith(prefix)

scan('bitecs-0.4-api', 'bitECS 0.4 removed defineComponent/defineQuery/Types.* — this code targets the old API and will not import',
  /\\b(defineComponent|defineQuery|defineSerializer|defineDeserializer|Types\\.[a-z])/)

scan('no-entity-classes', 'entity state belongs in bitECS components, not class fields',
  /^\\s*(export\\s+)?(abstract\\s+)?class\\s+\\w/, under('src/sim/'))

scan('no-state-on-views', 'a THREE.Object3D is a drawing of an entity, not the entity',
  /\\.userData\\b/, notUnder('src/assets/'))

scan('transform-writes', 'only the render system may write a view transform; gameplay writes the Transform component',
  /\\.(position|quaternion|rotation|scale)\\s*\\.\\s*(([xyzw]\\s*(=[^=]|\\+=|-=|\\*=))|(set|copy|setScalar|addScaledVector|applyQuaternion)\\s*\\()/, notUnder('src/render/'))

scan('sim-is-headless', 'src/sim must run with no DOM and no WebGL — it may not import three',
  /from\\s+['"]three['"]|require\\(['"]three['"]\\)/, under('src/sim/'))

scan('no-per-frame-alloc', 'allocating in a system body defeats the reason bitECS is here — use module-level scratch',
  /new\\s+(THREE\\.)?(Vector[234]|Quaternion|Matrix[34]|Euler|Color|Object3D|Box3|Ray)\\b/, under('src/sim/systems/'))

// Three of the checks above are scoped to src/sim/, so a game with no
// simulation layer would pass them by having nothing to inspect — the easiest
// way to satisfy the gate would be to skip the architecture entirely.
const simFiles = files.filter((f) => f.startsWith('src/sim/'))
const renderFiles = files.filter((f) => f.startsWith('src/render/'))
const layoutViolations = []
if (simFiles.length === 0) layoutViolations.push({ file: 'src/sim/', line: 0, text: 'no simulation layer — game state and systems belong here, not in the renderer' })
if (renderFiles.length === 0) layoutViolations.push({ file: 'src/render/', line: 0, text: 'no render layer — the Transform-to-Object3D sync belongs here' })
checks.push({ id: 'engine-layout', why: 'the sim/render split is the architecture; without it the other checks have nothing to inspect', ok: layoutViolations.length === 0, violations: layoutViolations })

let pkg = null
try {
  pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'))
} catch {
  /* reported below */
}
const depViolations = []
if (!pkg) depViolations.push({ file: 'package.json', line: 0, text: 'missing or unparseable' })
else {
  const all = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) }
  for (const [name, want] of Object.entries(DEPS)) {
    if (!all[name]) depViolations.push({ file: 'package.json', line: 0, text: name + ' is missing — required at ' + want })
    else if (all[name] !== want) depViolations.push({ file: 'package.json', line: 0, text: name + ' is ' + all[name] + ', must be pinned to exactly ' + want })
  }
  for (const name of Object.keys(all)) {
    if (BANNED_DEPS.test(name)) depViolations.push({ file: 'package.json', line: 0, text: name + ' is banned — we build our own stack, no React or R3F' })
  }
}
checks.push({ id: 'pinned-stack', why: 'the engine stack is pinned exactly and React is not part of it', ok: depViolations.length === 0, violations: depViolations })

// Every object the Reference Study named has to exist as a factory. Provenance
// is reported but not enforced: an entry the Asset Build could not crop is
// legitimately modelled by the implementer instead, and failing the build for
// that would only teach a worker to fake a state file.
const castViolations = []
const castNotes = []
let castRoot = null
try {
  const loops = fs.readdirSync(path.join(ROOT, 'reference'), { withFileTypes: true })
  for (const entry of loops) {
    const candidate = entry.isDirectory() ? path.join('reference', entry.name, 'manifest.json') : entry.name === 'manifest.json' ? 'reference/manifest.json' : null
    if (candidate && fs.existsSync(path.join(ROOT, candidate))) { castRoot = candidate; break }
  }
} catch {
  /* no pack in this workspace */
}
let cast = []
if (castRoot) {
  try {
    const parsed = JSON.parse(fs.readFileSync(path.join(ROOT, castRoot), 'utf8'))
    if (Array.isArray(parsed.cast)) cast = parsed.cast.filter((c) => c && typeof c.name === 'string')
  } catch {
    castViolations.push({ file: castRoot, line: 0, text: 'unparseable, so the cast could not be checked' })
  }
}
for (const member of cast) {
  const factory = 'src/assets/' + member.name + '.ts'
  if (!fs.existsSync(path.join(ROOT, factory))) {
    castViolations.push({ file: factory, line: 0, text: member.name + ' is in the cast but has no factory' })
    continue
  }
  if (!fs.existsSync(path.join(ROOT, '.img2threejs', member.name, 'state.json'))) {
    castNotes.push({ file: factory, line: 0, text: member.name + ' was modelled by hand — no img2threejs run behind it' })
  }
}
checks.push({ id: 'cast-built', why: 'every object the Reference Study named needs a factory to spawn from', ok: castViolations.length === 0, violations: castViolations, notes: castNotes })

const failed = checks.filter((c) => !c.ok)
const violationCount = failed.reduce((n, c) => n + c.violations.length, 0)
console.log(JSON.stringify({ ok: failed.length === 0, filesScanned: files.length, violationCount, checks }, null, 2))
process.exit(failed.length === 0 ? 0 : 1)
`

function starterPackageJson(name: string): string {
  return `${JSON.stringify(
    {
      name,
      private: true,
      version: '0.1.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc --noEmit && vite build',
        preview: 'vite preview',
        gate: 'node tools/engine-gate.mjs',
      },
      dependencies: ENGINE_DEPS,
      devDependencies: ENGINE_DEV_DEPS,
    },
    null,
    2,
  )}\n`
}

const TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      noUncheckedIndexedAccess: true,
      verbatimModuleSyntax: true,
      skipLibCheck: true,
      noEmit: true,
      lib: ['ES2022', 'DOM'],
    },
    include: ['src', 'tools'],
  },
  null,
  2,
)}\n`

/** The contract, on disk, for workers that read files rather than the prompt. */
export function contractMd(): string {
  return `# Engine — build contract

Generated by Gauntlet Gamesmith and rewritten every round. Do not edit: your changes
will be overwritten, and the gate enforces this file whatever it says here.

${engineContract()}
`
}

export interface ScaffoldResult {
  created: string[]
  refreshed: string[]
}

/**
 * Give a new workspace the engine before round one starts.
 *
 * Split deliberately into two kinds of file. The game's own files — the
 * manifest, the tsconfig, the source tree — are written only when absent, so a
 * round-seven workspace that has grown real dependencies is never clobbered.
 * The app's files — the contract and the gate — are rewritten every round,
 * because a contract that drifts is not a contract and a gate a worker can
 * edit to pass is not a gate.
 */
export function scaffoldEngine(workspaceDir: string, expectedWorkspace?: OwnedWorkspaceIdentity): ScaffoldResult {
  const created: string[] = []
  const refreshed: string[] = []
  const root = fs.lstatSync(workspaceDir)
  const identity = expectedWorkspace ?? { dev: root.dev, ino: root.ino }

  const parts = (rel: string): { directories: string[]; filename: string } => {
    const segments = rel.split('/')
    const filename = segments.pop()
    if (!filename) throw new Error('Engine scaffold path is missing a filename.')
    return { directories: segments, filename }
  }

  const writeIfAbsent = (rel: string, body: string): void => {
    const { directories, filename } = parts(rel)
    if (writeWorkspaceFileSafely(workspaceDir, identity, directories, filename, body, { replace: false }) === 'created') {
      created.push(rel)
    }
  }
  const rewrite = (rel: string, body: string): void => {
    const { directories, filename } = parts(rel)
    const result = writeWorkspaceFileSafely(workspaceDir, identity, directories, filename, body, { replace: true })
    if (result === 'created') created.push(rel)
    if (result === 'updated') refreshed.push(rel)
  }

  for (const dir of SRC_DIRS) ownedWorkspaceDirectory(workspaceDir, identity, dir.split('/'), true)

  writeIfAbsent('package.json', starterPackageJson(path.basename(workspaceDir).toLowerCase().replace(/[^a-z0-9-]+/g, '-')))
  writeIfAbsent('tsconfig.json', TSCONFIG)

  rewrite('CONTRACT.md', contractMd())
  rewrite('tools/engine-gate.mjs', GATE_SCRIPT)

  return { created, refreshed }
}
