import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export const OWNED_WORKSPACE_FILE_MARKER = '<!-- Generated by Gauntlet Gamesmith; app-owned. -->\n'
export const OWNED_YAML_FILE_MARKER = '# Generated by Gauntlet Gamesmith; app-owned.\n'
export type OwnedFileMarkerStyle = 'html' | 'yaml-frontmatter'

export interface OwnedPublicationLimits {
  /** Prefix shared by every immutable generation in this publication family. */
  managedPrefix: string
  maxFiles: number
  maxBytes: number
}

export interface OwnedWorkspaceIdentity {
  dev: number
  ino: number
}

const MAX_DIRECTORY_ENTRIES = 4_096
const MAX_PUBLICATION_BYTES = 16 * 1024 * 1024

export type SafeWorkspaceWriteResult = 'created' | 'updated' | 'unchanged' | 'preserved'

function markedContent(content: string, style: OwnedFileMarkerStyle): string {
  if (style === 'html') return `${OWNED_WORKSPACE_FILE_MARKER}${content}`
  if (!content.startsWith('---\n')) throw new Error('YAML-frontmatter app output must begin with a frontmatter delimiter.')
  return `---\n${OWNED_YAML_FILE_MARKER}${content.slice(4)}`
}

function validLeaf(value: string, label: string): void {
  if (!value || value === '.' || value === '..' || value.includes('/') || value.includes('\\')) {
    throw new Error(`Invalid app-owned ${label}.`)
  }
}

function contained(root: string, target: string): boolean {
  const relative = path.relative(root, target)
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative))
}

function assertWorkspaceRoot(workspaceDir: string, expected: OwnedWorkspaceIdentity): string {
  if (
    !Number.isSafeInteger(expected.dev)
    || expected.dev <= 0
    || !Number.isSafeInteger(expected.ino)
    || expected.ino <= 0
  ) throw new Error('App-owned publication requires a valid registered workspace identity.')
  const resolved = path.resolve(workspaceDir)
  const selected = fs.lstatSync(resolved)
  if (
    selected.isSymbolicLink()
    || !selected.isDirectory()
    || selected.dev !== expected.dev
    || selected.ino !== expected.ino
  ) throw new Error('Workspace root changed identity during app-owned publication.')
  const canonical = fs.realpathSync(resolved)
  const canonicalStat = fs.lstatSync(canonical)
  if (
    canonicalStat.isSymbolicLink()
    || !canonicalStat.isDirectory()
    || canonicalStat.dev !== expected.dev
    || canonicalStat.ino !== expected.ino
  ) throw new Error('Workspace root changed identity during app-owned publication.')
  return canonical
}

/** Resolve or create fixed app-owned directory components without following links. */
export function ownedWorkspaceDirectory(
  workspaceDir: string,
  expectedWorkspace: OwnedWorkspaceIdentity,
  segments: readonly string[],
  create: boolean,
): string {
  const workspace = assertWorkspaceRoot(workspaceDir, expectedWorkspace)
  let current = workspace
  for (const segment of segments) {
    validLeaf(segment, 'directory segment')
    assertWorkspaceRoot(workspaceDir, expectedWorkspace)
    current = path.join(current, segment)
    let stat: fs.Stats
    try {
      stat = fs.lstatSync(current)
    } catch (error) {
      if (!create || (error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
      fs.mkdirSync(current, { mode: 0o700 })
      stat = fs.lstatSync(current)
    }
    if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`App-owned directory is not a real directory: ${segment}`)
    current = fs.realpathSync(current)
    if (!contained(workspace, current)) throw new Error(`App-owned directory escapes the workspace: ${segment}`)
    assertWorkspaceRoot(workspaceDir, expectedWorkspace)
  }
  assertWorkspaceRoot(workspaceDir, expectedWorkspace)
  return current
}

function exactDescriptorContent(descriptor: number, size: number): Buffer {
  const result = Buffer.alloc(size)
  let offset = 0
  while (offset < size) {
    const read = fs.readSync(descriptor, result, offset, size - offset, offset)
    if (read === 0) throw new Error('App-owned publication ended before its declared size.')
    offset += read
  }
  return result
}

function writeExactDescriptorContent(descriptor: number, content: Buffer): void {
  let offset = 0
  while (offset < content.length) {
    const written = fs.writeSync(descriptor, content, offset, content.length - offset, offset)
    if (written === 0) throw new Error('App-owned workspace write made no progress.')
    offset += written
  }
}

/**
 * Safely create or refresh a fixed workspace file.
 *
 * Unlike immutable publications, engine support files have stable names. The
 * descriptor is opened without following links and its inode/link count is
 * checked immediately before and after mutation. Existing project-owned files
 * can be preserved by passing `replace: false`.
 */
export function writeWorkspaceFileSafely(
  workspaceDir: string,
  expectedWorkspace: OwnedWorkspaceIdentity,
  directorySegments: readonly string[],
  filename: string,
  content: string,
  options: { replace: boolean; mode?: number },
): SafeWorkspaceWriteResult {
  validLeaf(filename, 'filename')
  const expected = Buffer.from(content, 'utf8')
  if (expected.length > MAX_PUBLICATION_BYTES) throw new Error('App-owned workspace output is too large.')
  const assertRoot = (): void => { assertWorkspaceRoot(workspaceDir, expectedWorkspace) }
  const directory = ownedWorkspaceDirectory(workspaceDir, expectedWorkspace, directorySegments, true)
  const target = path.join(directory, filename)
  const noFollow = fs.constants.O_NOFOLLOW ?? 0

  let descriptor: number | null = null
  let created = false
  try {
    assertRoot()
    try {
      descriptor = fs.openSync(target, fs.constants.O_RDWR | noFollow)
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code
      if (code === 'ELOOP') throw new Error(`Refusing to follow a workspace output symlink: ${filename}`)
      if (code !== 'ENOENT') throw error
      try {
        descriptor = fs.openSync(
          target,
          fs.constants.O_RDWR | fs.constants.O_CREAT | fs.constants.O_EXCL | noFollow,
          options.mode ?? 0o600,
        )
        created = true
      } catch (createError) {
        if ((createError as NodeJS.ErrnoException).code !== 'EEXIST') throw createError
        descriptor = fs.openSync(target, fs.constants.O_RDWR | noFollow)
      }
    }

    assertRoot()
    const opened = fs.fstatSync(descriptor)
    const current = fs.lstatSync(target)
    if (
      !opened.isFile()
      || opened.nlink !== 1
      || current.isSymbolicLink()
      || !current.isFile()
      || current.nlink !== 1
      || current.dev !== opened.dev
      || current.ino !== opened.ino
    ) throw new Error(`Workspace output is not a unique regular file: ${filename}`)

    if (!created && !options.replace) return 'preserved'
    if (!created) {
      if (opened.size > MAX_PUBLICATION_BYTES) throw new Error(`Workspace output is too large to refresh safely: ${filename}`)
      if (opened.size === expected.length && exactDescriptorContent(descriptor, opened.size).equals(expected)) {
        if (options.mode !== undefined) fs.fchmodSync(descriptor, options.mode)
        return 'unchanged'
      }
      const beforeWrite = fs.fstatSync(descriptor)
      if (!beforeWrite.isFile() || beforeWrite.nlink !== 1) throw new Error(`Workspace output changed before refresh: ${filename}`)
      assertRoot()
      fs.ftruncateSync(descriptor, 0)
    }

    writeExactDescriptorContent(descriptor, expected)
    if (options.mode !== undefined) fs.fchmodSync(descriptor, options.mode)
    fs.fsyncSync(descriptor)
    const written = fs.fstatSync(descriptor)
    const after = fs.lstatSync(target)
    if (
      !written.isFile()
      || written.nlink !== 1
      || written.size !== expected.length
      || after.isSymbolicLink()
      || !after.isFile()
      || after.nlink !== 1
      || after.dev !== written.dev
      || after.ino !== written.ino
      || !exactDescriptorContent(descriptor, written.size).equals(expected)
    ) throw new Error(`Workspace output changed during refresh: ${filename}`)
    assertRoot()
    return created ? 'created' : 'updated'
  } finally {
    if (descriptor !== null) fs.closeSync(descriptor)
  }
}

function verifyExisting(target: string, filename: string, expected: Buffer, assertRoot: () => void): string {
  let descriptor: number | null = null
  try {
    assertRoot()
    descriptor = fs.openSync(target, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0))
    assertRoot()
    const opened = fs.fstatSync(descriptor)
    if (!opened.isFile() || opened.nlink !== 1 || opened.size !== expected.length || opened.size > MAX_PUBLICATION_BYTES) {
      throw new Error(`App-owned output is not the expected immutable publication: ${filename}`)
    }
    const actual = exactDescriptorContent(descriptor, opened.size)
    if (!actual.equals(expected)) throw new Error(`Refusing to replace an existing immutable workspace file: ${filename}`)
    const current = fs.lstatSync(target)
    if (current.isSymbolicLink() || current.dev !== opened.dev || current.ino !== opened.ino || current.nlink !== 1) {
      throw new Error(`App-owned output changed while it was verified: ${filename}`)
    }
    assertRoot()
    return target
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ELOOP') {
      throw new Error(`App-owned output is not the expected immutable publication: ${filename}`)
    }
    throw error
  } finally {
    if (descriptor !== null) fs.closeSync(descriptor)
  }
}

function enforcePublicationLimits(
  directory: string,
  limits: OwnedPublicationLimits,
  incomingBytes: number,
  assertRoot: () => void,
): void {
  validLeaf(limits.managedPrefix, 'publication prefix')
  if (!Number.isSafeInteger(limits.maxFiles) || limits.maxFiles < 1) throw new Error('Invalid app-owned publication file limit.')
  if (!Number.isSafeInteger(limits.maxBytes) || limits.maxBytes < 1) throw new Error('Invalid app-owned publication byte limit.')
  let seenEntries = 0
  let managedFiles = 0
  let managedBytes = 0
  assertRoot()
  const dir = fs.opendirSync(directory)
  try {
    for (;;) {
      const entry = dir.readSync()
      if (!entry) break
      seenEntries += 1
      if (seenEntries > MAX_DIRECTORY_ENTRIES) throw new Error('App-owned publication directory contains too many entries.')
      if (!entry.name.startsWith(limits.managedPrefix)) continue
      const candidate = path.join(directory, entry.name)
      const stat = fs.lstatSync(candidate)
      if (stat.isSymbolicLink() || !stat.isFile() || stat.nlink !== 1) {
        throw new Error(`App-owned publication family contains an unsafe entry: ${entry.name}`)
      }
      managedFiles += 1
      managedBytes += stat.size
    }
  } finally {
    dir.closeSync()
  }
  assertRoot()
  if (managedFiles >= limits.maxFiles || managedBytes + incomingBytes > limits.maxBytes) {
    throw new Error('App-owned publication retention limit reached; inspect and remove old immutable snapshots before retrying.')
  }
}

/**
 * Publish one immutable, collision-free workspace file.
 *
 * Existing bytes are never renamed, unlinked, or overwritten. An existing
 * pathname is reusable only when it is the same single-link regular file with
 * exactly the expected bytes. A failed or uncertain publication is deliberately
 * left in place for operator inspection; the bounded family quota prevents an
 * attacker from turning that policy into unbounded app-created state.
 */
export function publishOwnedWorkspaceFile(
  workspaceDir: string,
  expectedWorkspace: OwnedWorkspaceIdentity,
  directorySegments: readonly string[],
  filename: string,
  content: string,
  markerStyle: OwnedFileMarkerStyle = 'html',
  limits?: OwnedPublicationLimits,
): string {
  validLeaf(filename, 'filename')
  const assertRoot = (): void => { assertWorkspaceRoot(workspaceDir, expectedWorkspace) }
  const directory = ownedWorkspaceDirectory(workspaceDir, expectedWorkspace, directorySegments, true)
  const target = path.join(directory, filename)
  const expected = Buffer.from(markedContent(content, markerStyle), 'utf8')
  if (expected.length > MAX_PUBLICATION_BYTES) throw new Error('App-owned publication is too large.')

  try {
    return verifyExisting(target, filename, expected, assertRoot)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (limits) enforcePublicationLimits(directory, limits, expected.length, assertRoot)

  let descriptor: number | null = null
  try {
    assertRoot()
    try {
      descriptor = fs.openSync(
        target,
        fs.constants.O_WRONLY | fs.constants.O_CREAT | fs.constants.O_EXCL | (fs.constants.O_NOFOLLOW ?? 0),
        0o600,
      )
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'EEXIST') return verifyExisting(target, filename, expected, assertRoot)
      throw error
    }
    assertRoot()
    const opened = fs.fstatSync(descriptor)
    if (!opened.isFile() || opened.nlink !== 1) throw new Error('Immutable app-owned publication is not a unique regular file.')
    fs.writeFileSync(descriptor, expected)
    fs.fsyncSync(descriptor)
    const written = fs.fstatSync(descriptor)
    const current = fs.lstatSync(target)
    if (
      !current.isFile()
      || current.isSymbolicLink()
      || current.dev !== written.dev
      || current.ino !== written.ino
      || current.nlink !== 1
      || written.size !== expected.length
    ) {
      throw new Error(`App-owned output changed during immutable publication: ${filename}`)
    }
    assertRoot()
    return target
  } finally {
    if (descriptor !== null) fs.closeSync(descriptor)
  }
}

/** Publish a content-addressed immutable snapshot and return its exact path. */
export function publishOwnedWorkspaceSnapshot(
  workspaceDir: string,
  expectedWorkspace: OwnedWorkspaceIdentity,
  directorySegments: readonly string[],
  stem: string,
  extension: string,
  content: string,
  markerStyle: OwnedFileMarkerStyle,
  limits: OwnedPublicationLimits,
): string {
  validLeaf(stem, 'snapshot stem')
  if (!/^\.[a-z0-9]+$/.test(extension)) throw new Error('Invalid app-owned snapshot extension.')
  const digest = createHash('sha256').update(markedContent(content, markerStyle)).digest('hex')
  return publishOwnedWorkspaceFile(
    workspaceDir,
    expectedWorkspace,
    directorySegments,
    `${stem}-${digest}${extension}`,
    content,
    markerStyle,
    limits,
  )
}
